In [2]:
import numpy as np

In [3]:
a=np.array([13,4,2])

In [4]:
a

array([13,  4,  2])

In [5]:
a.shape


(3,)

In [6]:
a.ndim

1

In [7]:
a.size

3

In [8]:
a=np.array([[]])

In [9]:
a.ndim

2

In [10]:
b=np.array([[4,8,9]])

In [11]:
b.shape

(1, 3)

In [12]:
a.shape

(1, 0)

In [13]:
a=np.array([1,2,3])
b=np.array([4,8,9])
a-b

array([-3, -6, -6])

In [14]:
a+b

array([ 5, 10, 12])

In [15]:
a*b

array([ 4, 16, 27])

In [16]:
np.abs(a)

array([1, 2, 3])

In [17]:
a=np.array([90,1,4,10,2])

In [18]:
np.sort(a)

array([ 1,  2,  4, 10, 90])

In [19]:
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
a=np.array([1,4,7,8])
np.sum(a)

20

In [23]:
np.max(a)

8

In [24]:
np.min(a)

1

In [25]:
np.median(a)

5.5

In [26]:
a=np.arange(0,20,3)
a

array([ 0,  3,  6,  9, 12, 15, 18])

In [28]:
a=np.linspace(0,20,3)
a

array([ 0., 10., 20.])

In [30]:
a=np.zeros([3,2])
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [31]:
a=np.ones([3,2])
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])